name: Maven Dependency Check

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Dependency Updates
        run: |
          chmod +x ./csharp.sh
          ./csharp.sh
      - name: Commit Changes
        run: |
          git config --global user.email "tusharsao25@gmail.com"
          git config --global user.name "Tushar-2510"
          git add .
          git commit -m "Commit message from GitHub Actions"
          git push
          
